# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('annotation', models.CharField(blank=True, max_length=1024, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
