# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=20)),
                ('bg_image', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('annotation', models.CharField(blank=True, max_length=1024, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='content',
            name='body',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
        migrations.RemoveField(
            model_name='content',
            name='updated',
        ),
        migrations.AddField(
            model_name='content',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='units',
            field=models.ManyToManyField(through='core.Content', to='core.Unit'),
        ),
        migrations.AddField(
            model_name='content',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Section'),
        ),
        migrations.AddField(
            model_name='content',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Unit'),
        ),
    ]
