# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160911_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
