# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 10:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160912_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='column',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='content',
            name='order_id',
            field=models.IntegerField(default=0, help_text='Order in a column'),
        ),
    ]
