# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171202_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialresource',
            name='img_url',
            field=models.CharField(max_length=500),
        ),
    ]
