# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171202_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialResource',
        ),
    ]
