# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('uri', models.CharField(max_length=20)),
                ('order_id', models.IntegerField(default=0, help_text=b'Order id on its level')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='browser.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='SocialResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(max_length=500)),
                ('img_url', models.CharField(max_length=500)),
                ('order_id', models.IntegerField(default=0, help_text=b'Order in which logo appears in the stripe')),
            ],
        ),
    ]
